version: '3.9'

services:

 api:
   build: ./Payment.Api
   ports:
     - "5000:80"
   depends_on:
     - sqlserver
     - rabbitmq

 outbox:
   build: ./Payment.OutboxWorker
   depends_on:
     - rabbitmq
     - sqlserver

 worker:
   build: ./Payment.Worker
   depends_on:
     - rabbitmq

 gateway:
   build: ./Payment.GatewaySimulator
   ports:
     - "6000:80"

 rabbitmq:
   image: rabbitmq:3-management
   ports:
     - "15672:15672"

 sqlserver:
   image: mcr.microsoft.com/mssql/server:2022-latest
   environment:
     SA_PASSWORD: "Senha@123"
     ACCEPT_EULA: "Y"